### ISSUE TITLE
reified usage on Compose function crashes ParameterOrderDetector

### ISSUE THREAD

**Issue by kozaxinan** [slackhq/compose-lints#273]
```
@Composable
inline fun <reified T> MyComposable(text: String = "123", modifier: Modifier = Modifier, lambda: () -> Unit) : T { }
```

Running lint on provided reified compose function causes getText method to throw exception.

```
NullPointerException:ParameterOrderDetector$Companion$createErrorMessage$1.invoke(ParameterOrderDetector.kt:30)
ParameterOrderDetector$Companion$createErrorMessage$1.invoke(ParameterOrderDetector.kt:30)
StringsKt__AppendableKt.appendElement(Appendable.kt:85)←CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
ParameterOrderDetector$Companion.createErrorMessage(ParameterOrderDetector.kt:30)
ParameterOrderDetector.visitComposable(ParameterOrderDetector.kt:98)
ComposableFunctionDetector$createUastHandler$1.visitMethod(ComposableFunctionDetector.kt:33)
UElementVisitor$DispatchPsiVisitor.visitMethod(UElementVisitor.kt:
```

**Comment by yogurtearl** [comment]
Using version 1.3.1 of compose-lints. 
Seeing this similar stacktrace when upgrading from AGP 8.5.2 to AGP 8.60. 

Works fine on AGP 8.5.2, but getting this on AGP 8.6.0

Looks like this PR is not yet in the latest release? 

```
java.lang.NullPointerException: getText(...) must not be null
        at slack.lint.compose.ParameterOrderDetector$Companion$createErrorMessage$1.invoke(ParameterOrderDetector.kt:30)
        at slack.lint.compose.ParameterOrderDetector$Companion$createErrorMessage$1.invoke(ParameterOrderDetector.kt:30)
        at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
        at slack.lint.compose.ParameterOrderDetector$Companion.createErrorMessage(ParameterOrderDetector.kt:30)
        at slack.lint.compose.ParameterOrderDetector.visitComposable(ParameterOrderDetector.kt:98)
        at slack.lint.compose.ComposableFunctionDetector$createUastHandler$1.visitMethod(ComposableFunctionDetector.kt:33)
        at com.android.tools.lint.client.api.UElementVisitor$DispatchUastVisitor.visitMethod(UElementVisitor.kt:531)
        at com.android.tools.lint.client.api.UElementVisitor$DelegatingUastVisitor.visitMethod(UElementVisitor.kt:811)
        at org.jetbrains.uast.UMethod.accept(UMethod.kt:42)
        at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
        at org.jetbrains.uast.kotlin.AbstractKotlinUClass.accept(AbstractKotlinUClass.kt:213)
        at org.jetbrains.uast.internal.ImplementationUtilsKt.acceptList(implementationUtils.kt:15)
        at org.jetbrains.uast.UFile.accept(UFile.kt:89)
        at com.android.tools.lint.detector.api.UastLintUtilsKt.acceptSourceFile(UastLintUtils.kt:936)
        at com.android.tools.lint.client.api.UElementVisitor$visitFile$3.run(UElementVisitor.kt:215)
        at com.android.tools.lint.client.api.LintClient.runReadAction(LintClient.kt:1781)
        at com.android.tools.lint.client.api.LintDriver$LintClientWrapper.runReadAction(LintDriver.kt:2745)
        at com.android.tools.lint.client.api.UElementVisitor.visitFile(UElementVisitor.kt:212)
        at com.android.tools.lint.client.api.LintDriver$visitUastDetectors$1.run(LintDriver.kt:2046)
        at com.android.tools.lint.client.api.LintClient.runReadAction(LintClient.kt:1781)
        at com.android.tools.lint.client.api.LintDriver$LintClientWrapper.runReadAction(LintDriver.kt:2745)
        at com.android.tools.lint.client.api.LintDriver.visitUastDetectors(LintDriver.kt:2046)
        at com.android.tools.lint.client.api.LintDriver.visitUast(LintDriver.kt:2008)
        at com.android.tools.lint.client.api.LintDriver.runFileDetectors(LintDriver.kt:1282)
        at com.android.tools.lint.client.api.LintDriver.checkProject(LintDriver.kt:1068)
        at com.android.tools.lint.client.api.LintDriver.checkProjectRoot(LintDriver.kt:622)
        at com.android.tools.lint.client.api.LintDriver.access$checkProjectRoot(LintDriver.kt:174)
        at com.android.tools.lint.client.api.LintDriver$analyzeOnly$1.invoke(LintDriver.kt:445)
        at com.android.tools.lint.client.api.LintDriver$analyzeOnly$1.invoke(LintDriver.kt:442)
        at com.android.tools.lint.client.api.LintDriver.doAnalyze(LintDriver.kt:501)
        at com.android.tools.lint.client.api.LintDriver.analyzeOnly(LintDriver.kt:442)
        at com.android.tools.lint.LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:258)
        at com.android.tools.lint.LintCliClient$analyzeOnly$1.invoke(LintCliClient.kt:255)
        at com.android.tools.lint.LintCliClient.run(LintCliClient.kt:312)
        at com.android.tools.lint.LintCliClient.analyzeOnly(LintCliClient.kt:255)
        at com.android.tools.lint.Main.run(Main.java:1766)
        at com.android.tools.lint.Main.run(Main.java:282)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by yogurtearl** [comment]
I can confirm this is fixed with the latest `1.4.0-SNAPSHOT` as of today

**Comment by yogurtearl** [comment]
This wasn't a problem for us until AGP 8.6.0, so using AGP 8.5.2 might be a workaround for some.

**Comment by saket** [comment]
Downgrading AGP to 8.5.2 doesn't seem to be a workaround for my project.
